services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: waveflow-backend

    ports:
      - "8000:8000"


    environment:
      HITFM_COOKIE: ${HITFM_COOKIE:-}

    volumes:
      - waveflow-data:/app/data

    networks:
      - waveflow-net

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: waveflow-frontend

    depends_on:
      - backend

    ports:
      - "127.0.0.1:80:80"

    networks:
      - waveflow-net

    restart: unless-stopped

networks:
  waveflow-net:
    driver: bridge

volumes:
  waveflow-data:
